### ISSUE TITLE
Custom datetime format

### ISSUE THREAD

**Issue by max-sixty** [console-rs/indicatif#107]
Would you take a PR that allowed for passing a datetime string in the ProgressBar format? 

Would cover https://github.com/mitsuhiko/indicatif/issues/71 and more

I'm not sure exactly how it would fit with the format string. We could add it as an additional argument after the style argument; e.g. if were named `elapsed_chrono`

```
{spinner:.green} [{elapsed_chrono:.blue.%s:%ff}] [{bar:40.cyan/blue}] {bytes} ({eta})
```

...but is that too large an API change for the benefit?

**Comment by mitsuhiko** [comment]
Yep, would accept a PR.

**Comment by djc** [comment]
I think this is currently possible using custom formatters.
