### ISSUE TITLE
no support for progress bars instantiated after MultiProgress::join() is called

### ISSUE THREAD

**Issue by Gobiner** [console-rs/indicatif#111]
I'm trying to use indicatif's MultiProgress to draw progress bars for work happening on a background thread. I need to do some work to find out what the length of my progress bar should be, and that work is not instantaneous. I tried to follow along to the multi.rs example, but no progress bars would show up for me. I discovered that the root cause is that I was calling MultiProgress::join() before the other thread(s) had created a ProgressBar and added it to the outer MultiProgress.

I've created a test case, modified from the multi.rs example, that demonstrates my usage and issue: https://gist.github.com/Gobiner/ac9247e4c0caadcd37c7c3fcc50a4a97

**Comment by mmstick** [comment]
Encountered the same issue. It should be possible to interrupt the listener, to allow additional progress bars to be added. I will see if I can add this feature, as I'm in need of the same with an asynchronous fetcher that fetches an unknown number of files concurrently from a stream with an unknown length.

**Comment by mmstick** [comment]
So it seems that this is supported, even though it's not documented. The `MultiBar` is meant to be wrapped within an `Arc`, and passed to another thread. You can then begin adding progress bars to it while it is waiting. It works like so:

```rust
let complete = Arc::new(AtomicBool::new(false));
let progress = Arc::new(MultiProgress::new());

thread::spawn({
    let complete = Arc::clone(&complete);
    let progress = Arc::clone(&progress);
    move || {
        while !complete.load(Ordering::SeqCst) {
            let _ = progress.join();
           std::thread::sleep(Duration::from_millis(1000));
        }

        let _ = progress.join();
    }
});

... Add progress bars

complete.store(true, Ordering::SeqCst);
```

**Comment by djc** [comment]
As suggested, this is supported. Also, the threading model for `MultiProgress` changed in ways that hopefully make this even more obvious/easier.
