### ISSUE TITLE
Provide a way to clear the progress bar used by ProgressIterator.

### ISSUE THREAD

**Issue by cfredric** [console-rs/indicatif#142]
Currently, `ProgressIterator` provides methods that allow wrapping of an `Iterator` with a new `ProgressBarIter`. There is a method allowing for use of a custom `ProgressBar`, which allows for custom formatting, etc., but there is no way to specify whether the `ProgressBar` should be cleared when the iterator has been consumed. This forces the user to use a more awkward approach, keeping track of the `ProgressBar` separately and manually updating it inside the iterator.

This seems related to #6.

**Comment by djc** [comment]
Given that `ProgressBar`s can be cloned to gain handles to a particular `ProgressBar` and since the finalization style for progress bars can be customized, I think this scenario can now be supported. Please feel free to reopen if you think there's still something to improve here.
