### ISSUE TITLE
docs don't define the term "length"

### ISSUE THREAD

**Issue by sourcefrog** [console-rs/indicatif#145]
The API docs talk about the "length of the bar", eg in 

https://docs.rs/indicatif/0.13.0/indicatif/index.html#templates
> len: renders the total length of the bar as integer

but they don't explain whether this is the length of the visual bar, in characters, or the total amount of work to be done (e.g. the total amount of data to copy). From looking at the source it seems it's the latter. Would be nice to say this in the docs.

**Comment by vallentin** [comment]
*Just adding.*

It's the latter, and if you look at example just above, it shows `{pos}/{len}` hinting further that it's the *total amount of work to be done*.

```
bar.set_style(ProgressStyle::default_bar()
    .template("[{elapsed_precise}] {bar:40.cyan/blue} {pos:>7}/{len:7} {msg}")
    .progress_chars("##-"));
```

Also when you call a [ProgressBar::new()](https://docs.rs/indicatif/0.14.0/indicatif/struct.ProgressBar.html#method.new) you pass it `len`.

**Comment by djc** [comment]
I've tweaked the description in e3bd36b to hopefully be a little clearer.
