### ISSUE TITLE
print colored messages above the progress bar

### ISSUE THREAD

**Issue by sourcefrog** [console-rs/indicatif#146]
Following on from #41 - it would be great if there was a way to emit _colored_ or styled messages above the progress bar. 

It might be enough to just be able to temporarily hide it while I draw to the console, but perhaps it'd be easier and a natural fit to allow use of [`console::style`](https://docs.rs/console/0.9.1/console/#colors-and-styles) in messages?

**Comment by vallentin** [comment]
> if there was a way to emit colored or styled messages above the progress bar

It is possible, if you do it like this:

```rust
pb.println(&format!("Foo {} Baz", style("Bar").green()));
```

But I assume you would like a more integrated way, so doing `&format!(...)` isn't needed?

> be able to temporarily hide it while I draw to the console

This is a feature I'd like as well. I already do a bunch of:

```rust
pb.println(&format!(...));
pb.println(&format!(...));
pb.println(&format!(...));
```

I'd rather `hide/show` and `println!(...)`:

```rust
pb.hide();

println!(...);
println!(...);
println!(...);

pb.show();
```

**Comment by sourcefrog** [comment]
Oh, thanks for explaining it, that helps. I have a few other related wishes, although perhaps they should be separate bugs:

- println is disabled if the progress bar is disabled, but I think for many programs I'd like progress bars only on a tty, but messages always
- it'd be nice to integrate with rust `log` or similar

I see some of this is done in https://github.com/getsentry/sentry-cli/blob/master/src/utils/logging.rs.

**Comment by djc** [comment]
We now have `suspend()`, which I think should make this easier.

https://docs.rs/indicatif/0.17.0-rc.4/indicatif/struct.ProgressBar.html#method.suspend

Please file follow-up issues if you still think there's something to be improved here.
