### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by jagenheim** [console-rs/indicatif#152]
Either indicatif, or one of it's depencencies does not support static linking.

The binary is dynamically linked, even if using a static linked target. In my case it's armv7-unknown-linux-musleabihf.

**Comment by djc** [comment]
I'm unlikely to dig into this. If someone can provide more diagnostics on why this happens we can have a discussion about how to resolve it.

**Comment by jagenheim** [comment]
Sorry, I should've added more information when I created this issue. Because now, two years later, I don't remember at all what I tried to do. I'm fine with this being closed as a 'can not reproduce'.

**Comment by djc** [comment]
Thanks for the followup!
