### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by frondeus** [console-rs/indicatif#179]
Please consider keeping either `CHANGELOG.md` or putting changes into github release.

In my company, we are using indicatif for our internal tools, and it's great. However, the lack of information about what changed between 0.14 and 0.15 blocks me from upgrading to the newest version. Of course, I can compare tags and see what commits were made but it's far from pleasant.

**Comment by Stargateur** [comment]
https://github.com/mitsuhiko/indicatif/compare/0.14.0...0.15.0

**Comment by frondeus** [comment]
Yes as I mentioned I knew I could do that. And I did. This is only a small suggestion about minor QoL improvement.

**Comment by najamelan** [comment]
Especially, please list breaking changes in a changelog..

**Comment by djc** [comment]
I think those definitely count as changelogs.
