### ISSUE TITLE
cannot set remote drawing target

### ISSUE THREAD

**Issue by darkskygit** [console-rs/indicatif#196]
i want to draw progress both gui and console
then i must set a ProgressDrawTargetKind::Remote, but it is private
i can send a pull request if needed

**Comment by djc** [comment]
This isn't really what `Remote` was meant for, it's used exclusively for `MultiProgress` instances. On current main there is a `TermLike` trait you could implement which would allow you to receive updates. Going to close this for now, feel free to open a new issue if you think there's something which could be improved further.
