### ISSUE TITLE
The ETA is not updated by `enable_steady_tick`.

### ISSUE THREAD

**Issue by tangmi** [console-rs/indicatif#207]
When I have a `ProgressBar` with the estimated time in the output and `enable_steady_tick` called, I expect the ETA to increase if nothing is happening to the progress bar, but currently it requires me to manually call `ProgressBar::tick`.

I noticed that most methods on `ProgressBar` use [`ProgressBar::update_and_draw`](https://github.com/mitsuhiko/indicatif/blob/main/src/progress.rs#L762), which calls [`Estimate::record_step`](https://github.com/mitsuhiko/indicatif/blob/main/src/utils.rs#L41), updating the remaining time estimate. The [thread spawned for `enable_steady_tick`](https://github.com/mitsuhiko/indicatif/blob/main/src/progress.rs#L426) does not seem to do this, and I wonder if it should? I'm not sure if there's some other implications when adding this call to the `enable_steady_tick` thread.

Anyways, thanks for a wonderful library, it makes all my CLI tools so much nicer to use!

**Comment by djc** [comment]
Yeah, this is a bit of a degenerate case. In general the issue here would be that we if we try to estimate seconds per iteration, there isn't really an obvious way to get that for intervals of time where we did zero iterations.

If you have any thoughts about how we could improve this case, I'm happy to discuss further.

**Comment by tangmi** [comment]
Ah, I see the current code uses a ring buffer to calculate the average time of the last 16 updates. So if the `Estimator::record` is called a bunch of times with no progress, the buffer eventually fills with zeroes (from the snippet below) and we end up with an ETA of "now".

https://github.com/console-rs/indicatif/blob/b9d471441651210fc6d0cc9934f8ef304ec7b0b3/src/state.rs#L337-L341

A solution could be to let Estimator holistically calculate the ETA (instead of just the seconds per step), which would include it knowing the total elapsed time. That way, (I think) it has the overall average of seconds per step, rather than the rolling average. It could maybe blend the rolling average with the overall average based on how long ago the last non-zero update was?

Like you said, this is a bit of a degenerate case (and my intentions for a more accurate ETA was not critical--just to better judge when to get up to get a coffee), so I'm happy to have this close as "probably not worth it".

As an aside, it seems like `Estimator::prev` is never set anywhere, is that intended?

**Comment by tangmi** [comment]
I think you're right--I was just speculating what would happen if one put `record` calls in the Ticker loop.

Should `Estimator::prev` be set in `record`?

**Comment by djc** [comment]
> Should `Estimator::prev` be set in `record`?

Yes, you're right. I fixed that part up.

**Comment by tangmi** [comment]
Please feel free to close this with no action (especially if it feels like the work/benefit ratio is not good), or leave open for posterity.

The current behavior is not wrong in any way; the ETA is an _estimate_ after all 😄

**Comment by djc** [comment]
So, I think there's a solution for you here that works at least on main. There, you can write custom formatters that get access to the `ProgressState`. Among the API that `ProgressState` exposes, there are `elapsed()` and `pos()` getters. Together, I think you could use these to build your own ETA-like formatter that just calculates the progress based on a linear estimate that assumes each iteration takes the same amount of time (and will thus also grow longer if current iterations are taking longer -- that is, if there is no progress).

What do you think? Is that sufficient for your use case?

**Comment by tangmi** [comment]
I think that should be sufficient, please feel free to close

**Comment by djc** [comment]
Probably if you wanted to contribute a `linear_eta` formatter (or some other name if you can think of a better one -- maybe `uniform_eta`?) I'd also just merge that.
