### ISSUE TITLE
Incorrect Markdown on Libhunt Page

### ISSUE THREAD

**Issue by Wuelle** [console-rs/indicatif#208]
While this Issue is not directly related to this Repository, i still believe you can do something about it. This Repos page on ![https://rust.libhunt.com/indicatif-alternatives](https://rust.libhunt.com/indicatif-alternatives) is missing the Exclamation Marks before the Markdown images which results in the following:
![grafik](https://user-images.githubusercontent.com/58120269/97779242-0e514080-1b7d-11eb-8609-91364c0a5d68.png)

Note that I dont know exactly how much Influence on the Libhunt page you have. Im sorry to waste your time if this is not something you can fix.

**Comment by djc** [comment]
I don't think there's anything we can do about that (I also don't think the list of examples appears there anymore).
