### ISSUE TITLE
Support for multichar spinners, like the spinner library

### ISSUE THREAD

**Issue by snowe2010** [console-rs/indicatif#21]
The https://github.com/TheNeikos/spinner library has support for multichar spinners, like https://matthiasbeyer.github.io/imag/spinner/static.DANCING_KIRBY.html, but it does not have support for multiple bars/spinners. Is there any way to switch the `tick_chars` method to support strings, or maybe add a method called `.tick_strings` that takes a vec of strings?

**Comment by whentze** [comment]
I have implemented a rough version of this in [this branch](https://github.com/whentze/indicatif/commit/3b10680cc5b0dc6150b6d2057dc200e2e40783e5). Let me know if you have any comments on this.

**Comment by mibac138** [comment]
I believe this has been implemented in https://github.com/mitsuhiko/indicatif/pull/124, which is available from version 0.13.0

**Comment by djc** [comment]
Seems to be implemented. Feel free to reopen if there is still an issue here.
