### ISSUE TITLE
MultiProgress to support adding bars while already joining. 

### ISSUE THREAD

**Issue by scuzzycheese** [console-rs/indicatif#220]
I don't think this works currently, it seems you have to add them all before joining.

**Comment by mibac138** [comment]
It might be necessary to wrap the `MultiProgress` in an `Arc`, however except for that it should without any problems. Can you provide an example that doesn't work for you?

**Comment by nlinker** [comment]
@scuzzycheese Please, see the `multi-tree.rs` example, it shows how to add new bars on the fly.
