### ISSUE TITLE
How to use the pb.println to implement the function of log level？

### ISSUE THREAD

**Issue by JesseAtSZ** [console-rs/indicatif#223]
How to use the pb.println to implement the function of log level？

**Comment by djc** [comment]
I don't understand this issue. Please add more context on what you are trying to achieve, what you've tried and how it's failed.

**Comment by knassar702** [comment]
@djc I think he's talking about `log` macors in Rust
instead of using pd.println you can setup logger with your custom format like that `[%time] = %MODE%= %msg%`
```rust
CombinedLogger::init(ProgressLogger::new(Warn))
warn!("Hello")

[10-1-2021] = WARN = Hello
[###---- ]
```
