### ISSUE TITLE
Too many spinners causes integer underflow when run in Windows Terminal

### ISSUE THREAD

**Issue by obsgolem** [console-rs/indicatif#225]
Creating more spinners than there are lines on the screen appears to fail in the specific case of running in Windows Terminal. The error I get from this is 

```
thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\josia\.cargo\registry\src\github.com-1ecc6299db9
ec823\console-0.14.0\src\windows_term.rs:152:32
```

I stepped through this in the debugger, and it appears that the issue happens because you are trying to use the Windows API in a console that is configured with a PTY. In this scenario, the Windows API reports an incorrect number of lines in the console. This does not appear to happen with a native command prompt, where the (internal) window size seems to expand as you add more lines.

```rust
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use std::sync::Arc;

fn main() {
    let prog = Arc::new(MultiProgress::new());
    prog.set_move_cursor(true);

    let temp = (0..40)
        .into_iter()
        .map(|x| {
            let style = ProgressStyle::default_spinner();
            let pb = prog.add(ProgressBar::new_spinner()).with_style(style);
            pb.enable_steady_tick(66);

            pb.set_message("Running");
            pb
        })
        .collect::<Vec<_>>();
    prog.join().unwrap();
}
```

This issue is known already on console: https://github.com/mitsuhiko/console/issues/61.  I suggest updating the tty detection code to switch to VT when it is enabled, see https://docs.microsoft.com/en-us/windows/console/getconsolemode

**Comment by obsgolem** [comment]
I put in a fix for this downstream: https://github.com/mitsuhiko/console/pull/81

**Comment by djc** [comment]
Going to close this, thanks for fixing it upstream!
