### ISSUE TITLE
MultiProgress::join doesn't take into account dynamic addition of spinners

### ISSUE THREAD

**Issue by obsgolem** [console-rs/indicatif#227]
If a `MultiProgress` object is joined before it has any spinners added to it, then it returns immediately and has to be rejoined if more spinners or other progress bars are added later. This is problematic during a dynamic work discovery scenario, where new spinners or progress bars need to be added as more work is found. A workaround for this is below:

```
let prog = Arc::new(MultiProgress::new());
let prog2 = Arc::downgrade(&prog);
thread::spawn(move || {
    while let Some(x) = prog2.upgrade() {
        x.join().unwrap();
    }
});
```
This ensures that the progress bars keep running until `prog` drops. I feel like this functionality should either be native to `MultiProgress` or some of the gotchas with multithreading should be documented.

**Comment by marienz** [comment]
I'm experimenting with removing `MultiProgress::join` entirely in #231 to solve more or less this problem.

**Comment by djc** [comment]
Since #231 has landed, I'm going to close this. Feel free to reopen if you still think there is an issue.
