### ISSUE TITLE
Set position and length together

### ISSUE THREAD

**Issue by giggio** [console-rs/indicatif#236]
Sometimes there is need to adjust position and length together. Any one you do individually will set the progress bar to an incorrect amount, until the second one is set.
To enable this scenario a method like `set_length_and_position` would solve the problem, as it would draw only after both are set.

**Comment by cassiersg** [comment]
Furthermore, it would be good to add a `set_length_and_position_with`, that could be used as follows:
```rust
bar.set_length_and_position_with(|current_length, current_position| {
    let new_length = ...;
    let new_position = ...;
   return (new_length, new_position);
});
```
This would enable to to the change atomically (for example incrementing the length and/or position), which is not possible currently in case of concurrent execution (except by adding and additional lock, but this is annoying to do and duplicates the lock that is already in the `ProgressBar`). Such a method would subsume #236.

**Comment by djc** [comment]
d198f809c56868c8e998077eda3e3652e3a1c5fa adds a `ProgressBar::update()` method that allows the caller to mutate the `ProgressState` directly.
