### ISSUE TITLE
Canonical way to disable progress bar for a --quiet mode

### ISSUE THREAD

**Issue by Walther** [console-rs/indicatif#238]
Request for docs: What would be the canonical way to optionally disable the progress bar in the code of a CLI application, if a parameter like `--quiet` has been passed in (and parsed by a parameter handling library)?

Somewhat tangentially related to https://github.com/mitsuhiko/indicatif/issues/170 as well, ideally this would not just disable the visual output but also remove any performance hits as well - but not sure how feasible this would be.

Thanks!

**Comment by mibac138** [comment]
You can use `pb.set_draw_target(ProgressDrawTarget::hidden())` to disable a progress bar's output, however this won't remove all of the performance impact.

**Comment by djc** [comment]
I think `set_draw_target()` fixes the output issue. I'm not sure it would make sense to internally fix the issue of removing all performance hits; you should probably just push an `Option<ProgressBar>` around if you want to make all of it optional. Going to close this for now, feel free to reopen if you still want to discuss more.

**Comment by Walther** [comment]
Thanks for the help!

To reiterate from the original - would it be possible to place these insights in a prominent place in the documentation? If these are indeed the officially endorsed views of the library, paraphrased:
1. while you could technically use `set_draw_target()` as a simple way to hide the bar, it will just hide the output and any performance impact of the progress tracking will still be there, so it is *not recommended*
3. a pattern of using `Option<ProgressBar>` is the recommended solution if you want to make it optional, as it will fully disable the tracking. [insert code example here, with both the bar itself and the relevant `bar.inc(1)` calls within some function optional-ized in a way that keeps the compiler happy]

Having a `--quiet` flag (or similar) is a best-practices item for CLI applications, so it would be nice to have the docs recommend a known-good way of doing it!

**Comment by djc** [comment]
`set_draw_target()` will decrease the performance impact, but it will not be zero.

Would you mind proposing some doc improvements as a PR? I'd be happy to review.
