### ISSUE TITLE
Feature request: Color styling depending on success

### ISSUE THREAD

**Issue by matthiasbeyer** [console-rs/indicatif#239]
Hi,

I have a program where the process represented by a progress bar might result in an error. I would like to have a functionality to set the message for that bar to a (for example) red string.

Right now that seems not to be possible, hence this is a feature request for such a feature.

**Comment by djc** [comment]
You can set the finish style to change the message, which could include a different color. Would that be sufficient? If not, please make a proposal for what kind of API you would like to see for this.

**Comment by matthiasbeyer** [comment]
Sounds good. Thanks for coming back to this!
