### ISSUE TITLE
examples/download.rs doesn't show actuall progress bar (on Windows)

### ISSUE THREAD

**Issue by Amomum** [console-rs/indicatif#263]
It compiles and runs just fine but shows no progress bar, just empty square brackets (spinner is fine):

![image](https://user-images.githubusercontent.com/4990494/113214730-8d5cb900-9282-11eb-8a69-9df98c481ac1.png)

This happens in git bash and in cmd on Windows 7

**Comment by piegamesde** [comment]
The format string is missing a colon. Try `{wide_bar:.cyan/blue}` and it should work again. Maybe the `template()` function should do some early parsing and report format errors right away.

**Comment by Amomum** [comment]
@piegamesde progress bar did appear but it looks like that:

![image](https://user-images.githubusercontent.com/4990494/114273556-2cbc4180-9a23-11eb-8fe4-cc6b32f894aa.png)

i.e. progress-bar is not re-drawn. I suppose that is a different issue :)

It sure would be nice to know if a format string contains errors; looks like right now they are just quietly ignored?

**Comment by djc** [comment]
The template parser is now (a3c1829f6f5edf76181b1951a1f3e9b91587bdd0) fallible and will return an error on failure to parse.
