### ISSUE TITLE
Order of calling ProgressBar::set_{prefix, message, style}

### ISSUE THREAD

**Issue by Arnavion** [console-rs/indicatif#28]
Calling `set_message` or `set_prefix` before `set_style` causes the style passed to `set_style` to not take effect for the first draw. Perhaps `set_style` should also call `update_and_draw` ? Otherwise it would be nice to document somewhere that the user should either call `set_style` before any other function or use `tick` to force a redraw after changing the style.

**Comment by djc** [comment]
This was documented in f0358d5ea7b465bc1ca8c3fb0061cc6ff929973a.
