### ISSUE TITLE
Document performance metrics

### ISSUE THREAD

**Issue by Halkcyon** [console-rs/indicatif#282]
Coming from Python, `tqdm` has worked very hard to have <100ns/iter performance overhead.  Has `indicatif` documented its performance profile?

**Comment by djc** [comment]
No, it has not. Performance should be much improved on the main branch compared to 0.16 though. In a quick test, it seems to get 0.5μs/iter in a worst-case test (running the fastbar example in release mode).

**Comment by djc** [comment]
After reading this I had to do some more optimizations. With #390 it seems the overhead is down to about 25ns/iter (on my machine) for `inc()` calls. Going to close this for now.
