### ISSUE TITLE
Deferred multiprogress updates can run away with memory

### ISSUE THREAD

**Issue by calmofthestorm** [console-rs/indicatif#288]
`Multiprogress`'s current drawing model queues updates which are then drawn later. This can lead to runaway memory usage if the updates aren't actually being drawn.

I can sort of see the argument that this is WAI, or more accurately, that it would be better addressed in the context of #33. But it does seem odd to me that we queue up updates, for, e.g., `inc(1)` rather than just retaining the last one. Now I'm wondering if this could also cause flickering issues or similar (e.g. #226 ), if deferred updates would be applied all at once in a bunch should the accumulate for some reason rather than one update to bring to the current state.

For example, the below will eventually exhaust memory:

```
fn main() {
    let multiprogress = indicatif::MultiProgress::new();
    let bar = indicatif::ProgressBar::new(100);
    let bar = multiprogress.add(bar);
    let mut j = 0;
    // for _ in 0..10000 {
    loop {
        j = (j + 1) % 50;
        // bar.set_position(j);
        bar.inc(j);
    }
}
```

If we ran `multiprogress.join()` in a separate thread concurrently to actually draw it, then the updates would be drawn and not accumulate. I ran into this because I was not calling `join()` as a way to hide progress bars (see also #238 for the correct way to do this).

**Comment by djc** [comment]
We're currently working on #284, can you review how that influences this issue?

**Comment by calmofthestorm** [comment]
#284 would fix this.

I patched in the PR and memory stays flat and low as expected. I am very happy to see #284 land and wish you the best of luck; this issue is a minor annoyance at most, but needing a threading model for multiprogress has been inconvenient in other ways, and  delegating to the child updates is both an effective solution to that and an elegant design.

I look forward to using the new, simpler API.

**Comment by djc** [comment]
Thanks for the feedback! I'll keep this open for a bit and probably close it when #284 lands.
