### ISSUE TITLE
ProgressBar is not updated/draw on .tick()

### ISSUE THREAD

**Issue by Lukas1818** [console-rs/indicatif#321]
The PIrogressBar will not be drawn, if I did call `pb.tick()`. But If a thread finish, the message, will be shown.
```rust	
	let pb = ProgressBar::new(stickerpack.stickers.len() as u64);
	pb.set_style(
		ProgressStyle::default_bar()
			.template("[{wide_bar:.cyan/blue}] {pos:>3}/{len} {msg}")
			.progress_chars("#> "),
	);
	stickerpack
		.stickers
		.par_iter()
		.progress_with(pb.clone())
		.enumerate()
		.map(|(i, sticker)| {
			pb.set_message(format!("download sticker {}", sticker.file_id))
			pb.tick();
			...
```

tested version: 0.16.2;    0.17.0-beta.1

**Comment by djc** [comment]
If you make a self-contained reproduction I might be able to investigate this.

**Comment by djc** [comment]
Going to close for lack of followup. Feel free to reopen if you have an actionable reproduction.
