### ISSUE TITLE
Is it possible to add/change a separator between bytes and their units?

### ISSUE THREAD

**Issue by firasuke** [console-rs/indicatif#344]
As the title says, is it possible to add/change a separator (e.g. space) between the displayed keys (e.g. bytes) and their units (e.g. KiB)?

For example, when using `"{bytes}"` I get `511.25KiB` when I want `511.25 KiB`.

I found this #301 but it seems that no new release happened following that commit.

Thanks!

**Comment by djc** [comment]
This is possible with the 0.17 rcs, or follow #318 to track when the final version is released.
