### ISSUE TITLE
Why is there an additional space in the end?

### ISSUE THREAD

**Issue by firasuke** [console-rs/indicatif#348]
It seems that regardless of the template of the progress bar, there's always an extra space " " in the end.

Is this behavior intended? If so, can it be changed?

Thanks!

**Comment by djc** [comment]
I don't know what the original rationale is exactly, but it seems to be necessary: #342.

**Comment by sigmaSd** [comment]
Im not sure if there is an alternative, without that space issue like the ones pointed above arises, maybe we can only add a space when the bar size is the terminal width size or just hide the cursor or just keep this behaviour

**Comment by firasuke** [comment]
I think it will be better to make both of them optional, but it shouldn't default to add an extra space in the end, and maybe provide an option to hide the cursor as well.

**Comment by sigmaSd** [comment]
Actually I think 342 is not solved with the space, if the user tries to use println after a bar that is less then the terminal width it will exibit the original issue behaviour

So the space hack is invalid its needs to be rwmoved

This cycles back to the original issue we made the progressbar not have a new line at the end, I think its simply the tradeoff without a newline the user will have 342 behaviour and he will simply need to be aware of it so he can use an extra println

Personaly I think the tradeoff is worth it, the extra new line always looked weird, and the fix from the user side if neededis simple

**Comment by sigmaSd** [comment]
Also we can make the default situation better by making the default bar fill the whole terminal width instead of width - 1

**Comment by sigmaSd** [comment]
So it should look something like this:
```patch
diff --git a/src/draw_target.rs b/src/draw_target.rs
index 1bb9c56..2803a0d 100644
--- a/src/draw_target.rs
+++ b/src/draw_target.rs
@@ -396,9 +396,6 @@ impl ProgressDrawState {
             } else {
                 // Don't append a '\n' if this is the last line
                 term.write_str(line)?;
-                // Also append a ' ' to keep the original chars count
-                // This is important if the line was meant to fill the entire width
-                term.write_str(" ")?;
             }
         }
         Ok(())
diff --git a/src/style.rs b/src/style.rs
index f446e14..df047ee 100644
--- a/src/style.rs
+++ b/src/style.rs
@@ -390,7 +390,7 @@ impl<'a> WideElement<'a> {
         state: &ProgressState,
         buf: &mut String,
     ) -> String {
-        let left = state.width().saturating_sub(measure_text_width(&cur));
+        let left = state.width().saturating_sub(measure_text_width(&cur)) + 1;
         match self {
             Self::Bar { alt_style } => cur.replace(
                 "\x00",
```

The wide elements gets +1 so they can fill the removed '\n' position, I'm not sure if that's the  best place to add it but it seems to work.

These math parts are tricky hopefully someone can confirm or not if this is correct
