### ISSUE TITLE
indicatif's defaults bottleneck the application on terminal output

### ISSUE THREAD

**Issue by untitaker** [console-rs/indicatif#363]
default usage of indicatif currently has horrible performance when many items are processed in short time. there's issues like #170 which say this is due to global locks, but I found that even `set_draw_rate(1000)` can improve performance by an order of magnitude for certain applications.

I propose that indicatif picks better defaults for draw rate even if it's still printing to the display every millisecond, because the current default experience is broken IMO. Even if it goes as far as enabling steady tick by default to compensate for potential side effects of draw rate, I think spawning an extra thread by default would still be a preferrable default behavior over bottlenecking the entire application on terminal output.

**Comment by djc** [comment]
Have you tried this with main? There's a bunch of performance improvements.

**Comment by djc** [comment]
(I do think it might make sense to default to a draw rate of, say, 100. Want to submit a PR?)

**Comment by untitaker** [comment]
I can try main branch but I think unless the draw rate default changed or indicatif got _significantly faster_ in `tick`, there's no way it would change anything

**Comment by untitaker** [comment]
Very interesting, it seems that indicatif _mostly_ removed whatever bottleneck drawing on the terminal had on master. I can still see a slight improvement with `set_draw_rate` instead of drawing on every update, but it's more like 10% overhead instead of 2000% overhead

**Comment by djc** [comment]
It's probably #319, or maybe #361.

**Comment by untitaker** [comment]
>(I do think it might make sense to default to a draw rate of, say, 100. Want to submit a PR?)

there's unresolved questions because "draw rate" currently takes precedence over "draw delta". With a default for "draw rate", draw delta... cannot be set anymore? Unsure.

**Comment by djc** [comment]
How about you make `draw_rate` an `Option<u64>` that defaults to `Some(100)` and is overwritten with `None` if the `draw_delta` is set? (And change the documentation accordingly.)

**Comment by djc** [comment]
I've implemented a default draw rate in 9df7ab3255de945a5f8a221aff8587591ef4d113.

**Comment by untitaker** [comment]
Thanks! Sorry, didn't get around to contributing this

**Comment by djc** [comment]
It's fine. My initial fix seems to have caused some regressions, so still investigating some follow up.
