### ISSUE TITLE
Progress bar *as logger*

### ISSUE THREAD

**Issue by jqnatividad** [console-rs/indicatif#366]
Originally posted by @rubdos in https://github.com/console-rs/indicatif/issues/92#issuecomment-867579570_

Now that #92 is closed, opening a new issue of progress bar as logger.

Fleshing this out a bit more, it would be great if we can use logging messages using some special syntax to:
* pass the record count 
* increment progress
* finish progress

It'd be awesome if the progress logger is running on a separate thread to update the progress bar.

This would make it very easy to incorporate indicatif by leveraging logging. I'm partial to leveraging flexi_logger for this as it has async support.

**Comment by djc** [comment]
This is a little too abstract for me, and I don't think I have any use cases that would require this. Feel free to make more concrete proposals for changes you'd like to make either as a description of a few sentences about the changes you'd like to make or just as a PR.
