### ISSUE TITLE
Replacement for set_draw_delta()?

### ISSUE THREAD

**Issue by jqnatividad** [console-rs/indicatif#393]
With 0.17.0-rc.6, `set_draw_delta` is no longer. 

In my application using 0.16.2, I used it effectively to limit updates to every 1% of progress with an `inc(1)` inside a loop with millions of iterations by doing `set_draw_delta( record_count / 100);`.

I understand that with 0.17, a lot of refactoring was done to improve performance.

Is it no longer necessary to use `set_draw_delta` then and I can just do `inc(1)` for a loop with millions of rows and the indicatif overhead will be minimal?

**Comment by djc** [comment]
Yes, the idea is that it is no longer necessary. Effectively there's still rate limiting in place for drawing to the terminal, which defaults to drawing every 50ms (but this can be customized by setting calling `ProgressDrawTarget::std{out,err}_with_hz()`. I'd be curious to hear if this approach works for your use case!

**Comment by djc** [comment]
@jqnatividad any conclusions from your tests?

**Comment by jqnatividad** [comment]
Sorry @djc, didn't get around to do the tests. Will do so this week with the latest rc.

**Comment by djc** [comment]
Thanks!

**Comment by agourlay** [comment]
Adding my data point to this issue.

I had a similar issue and I was able to apply `ProgressDrawTarget::stdout_with_hz` to rate limit the refresh rate on a multi-progress bar. 

source: using `0.17.0-rc.10` https://github.com/agourlay/dlm/commit/72495f5faee73ac8611e5e4032ea257d7525058d

**Comment by djc** [comment]
@agourlay thanks for the data! What rate did you limit it to, and how did that impact the indicatif overhead for your workload?

**Comment by agourlay** [comment]
@djc I do not see a difference in CPU utilization between before and after applying the refresh rate patch. 
My application is IO bound so I don't think I would see any significant changes anyway :)

**Comment by djc** [comment]
Thanks, that makes sense! So you like to play it safe with your low refresh rate limit, but it seems like the defaults would actually work just as well for your use case.

**Comment by agourlay** [comment]
Yes the default refresh rate of 50ms works fine technically, I just find it a tad too fast in terms of UI for my use case.

**Comment by jqnatividad** [comment]
Hi @djc , sorry didn't get back as promised, but just wanted to confirm that 0.17.0 is awesome! 
I no longer need to futz with tweaking refresh rate, no matter how large the job is.
And as for what I'm using indicatif for - I use it in extensively in [qsv](https://github.com/jqnatividad/qsv#qsv-ultra-fast-csv-data-wrangling-toolkit) - a CSV data-wrangling toolkit forked from [xsv](https://github.com/burntsushi/xsv).
Thanks heaps for everything you do for the Rust ecosystem!!!

**Comment by djc** [comment]
Sounds good, thanks for the confirmation!
