### ISSUE TITLE
Strange behavior of spinners and enable_steady_tick?

### ISSUE THREAD

**Issue by chris-laplante** [console-rs/indicatif#397]
Try running this code:

```
use std::thread;
use std::time::Duration;

use indicatif::{ProgressBar, ProgressFinish};

fn main() {
    let mut spinner: Option<ProgressBar> = None;

    for _ in 0..100 {
        let new_spinner = ProgressBar::new_spinner()
            .with_finish(ProgressFinish::AndLeave)
            .with_message("doing stuff");
        new_spinner.enable_steady_tick(Duration::from_millis(10));
        thread::sleep(Duration::from_millis(500));
        spinner.replace(new_spinner).map(|t| t.finish());
    }
}
```

Two things happen that I can't explain. 

1) The first spinner is not actually finished (red arrow)
2) Occasionally, some of the other spinners also don't finish. (blue arrow)

(1) happens even if you change the loop to only go from 0..2.

![image](https://user-images.githubusercontent.com/40474653/158625277-9ce98f47-c92a-456a-9749-ce2c235f6af8.png)

I question whether there is some kind of race condition somewhere in Ticker.

**Comment by djc** [comment]
Hmm, I think your example code is not doing what you expect it to do. If you add some debug stuff like this:

```
diff --git a/src/state.rs b/src/state.rs
index 7e8a30f..265af6f 100644
--- a/src/state.rs
+++ b/src/state.rs
@@ -32,6 +32,7 @@ impl BarState {
     /// in the [`ProgressStyle`].
     pub(crate) fn finish_using_style(&mut self, now: Instant, finish: ProgressFinish) {
         self.state.status = Status::DoneVisible;
+        println!("\n\nfinish {}\n\n", self.style.message);
         match finish {
             ProgressFinish::AndLeave => self.state.pos.set(self.state.len),
             ProgressFinish::WithMessage(msg) => {
@@ -297,6 +298,7 @@ impl Ticker {
         thread::sleep(self.interval);
         while let Some(arc) = self.weak.upgrade() {
             let mut state = arc.lock().unwrap();
+            println!("ticker locked: {}", state.style.message);
             let interval = match state.ticker {
                 Some((interval, _)) if !state.state.is_finished() => interval,
                 _ => return,
```

And change the message like `.with_message(format!("doing stuff {}", i))` you can see that after the first iteration of the loop there are always two spinners alive at the same time, so I think they could be writing to the terminal in more or less arbitrary order.

I feel like if you want to have multiple `ProgressBar`s live at the same time, the resulting output will be undefined unless you use a `MultiProgress`?

(I tested and this also seemed to be somewhat broken on 0.16.1 -- if you think it's a regression, maybe bisect it?)

**Comment by chris-laplante** [comment]
> I feel like if you want to have multiple `ProgressBar`s live at the same time, the resulting output will be undefined unless you use a `MultiProgress`?
>
> (I tested and this also seemed to be somewhat broken on 0.16.1 -- if you think it's a regression, maybe bisect it?)

Good point - the actual code is using `MultiProgress`, so I should have included it in my reproducer here :). I will work on tracking down the cause.

**Comment by chris-laplante** [comment]
OK I can confirm that restructuring the code to use `MultiProgress` (and adding a final line to `take` and `finish` the last spinner) solves the problem:

```
use std::thread;
use std::time::Duration;

use indicatif::{MultiProgress, ProgressBar, ProgressFinish};

fn main() {
    let mp = MultiProgress::new();
    let mut spinner: Option<ProgressBar> = None;

    for i in 0..20 {
        let new_spinner = mp.add(
            ProgressBar::new_spinner()
                .with_finish(ProgressFinish::AndLeave)
                .with_message(format!("doing stuff {}", i)),
        );
        new_spinner.enable_steady_tick(Duration::from_millis(10));
        spinner.replace(new_spinner).map(|t| t.finish());
        thread::sleep(Duration::from_millis(500));
    }

    spinner.take().unwrap().finish();
}
```

I guess I'm still a little confused why the final call to `finish` is necessary though - I thought the `Drop` impl for `BarState` was supposed to do that automatically?

**Comment by djc** [comment]
The timing situation there is interesting. Dropping the inidividual `ProgressBar` instances will draw, but it will draw into the `MultiProgressState`. By virtue of reverse drop order, `spinner` should get dropped before `MultiProgress` (and its `MultiProgressState`), but then there are also the ticker threads that hold on to a `Weak<Mutex<BarState>>`. Might be worth it to instrument the drop calls to see if there's something that can be improved there?

**Comment by chris-laplante** [comment]
Sounds good, I will investigate. I've blocked off tomorrow to work on indicatif stuff (as well as baking some cupcakes :)).
