### ISSUE TITLE
Docs don't include ParallelProgressIterator

### ISSUE THREAD

**Issue by nipunn1313** [console-rs/indicatif#398]
I was expecting the docs to show ParallelProgressIterator here
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1300387/158685207-2f297cc9-bf42-4706-868d-286dfab9a16f.png">

https://docs.rs/indicatif/latest/indicatif/index.html

Might be that the docs need to be built with features on?

**Comment by djc** [comment]
#399 should improve on this.
