### ISSUE TITLE
Possible to truncate beginning of wide_msg?

### ISSUE THREAD

**Issue by 1Dragoon** [console-rs/indicatif#400]
I'm wanting to have wide_msg truncate the beginning of the string rather than the end of the string.

So basically if we use this sentence as an example, truncating to 40 characters:

```
an example, truncating to 40 characters:
```

As opposed to the existing behavior:

```
So basically if we use this sentence as 
```

I tried to find a way to determine what the current width of wide_msg is so I could manually do this, but I didn't see any obvious public exposure of it.

**Comment by djc** [comment]
Yeah, this currently can't be done. We could maybe do this by changing truncation to take the alignment flag into account.

**Comment by djc** [comment]
#402 should make this possible.
