### ISSUE TITLE
MultiProgress example does not draw the last update

### ISSUE THREAD

**Issue by djc** [console-rs/indicatif#411]
When running `cargo run --example multi-tree-ext`, I've noticed that the last update sometimes doesn't get drawn. This is intermittent but fairly easy to reproduce, I've usually seen it happen every two or three runs.

Expected output:

```
[32/32]   ✔ the
[32/32]     ✔ quick
[32/32]       ✔ brown
[32/32]         ✔ fox
[32/32]           ✔ jumps
[32/32]             ✔ over
[32/32]               ✔ a
[32/32]                 ✔ lazy
[32/32]                   ✔ dog
████████████████████████████████████████  585/585
```

Actual output:

```
[32/32]   ✔ the
[32/32]     ✔ quick
[31/32]       ⠚ brown
[32/32]         ✔ fox
[32/32]           ✔ jumps
[32/32]             ✔ over
[32/32]               ✔ a
[32/32]                 ✔ lazy
[32/32]                   ✔ dog
███████████████████████████████████████░  574/585
```

Note that on current main, there are multiple issues with `multi-tree-ext`, so your output may not look like this at all. Bisection seems to point to 57e6ee282d5dd71f7846bd28e3f0369fd3f6d452 as the first commit where this started happening, which makes sense as that was a rather invasive change, but I haven't quite been able to track down the cause.

**Comment by djc** [comment]
I can no longer reproduce this with #414.

**Comment by lmapii** [comment]
@djc I'm sorry if I'm hijacking this issue for a simple question: How do you create this kind of output with indicatif? I'm currently looking into this package for a CLI tool, and in some scenarios it is useful to still get the full output, e.g., for debugging (`./target/debug/examples/yarnish > test.txt 2>&1`). So far I didn't find an option to "spread" the output, but I'll keep looking.

**Comment by lmapii** [comment]
@djc thanks a lot for the fast reply. Yeah #87 is actually really interesting. What I'm trying to achieve is essentially a "--progress plain" as docker does. Maybe once I'm really fit with rust I could contribute but so far I've only written a single application. Sorry for abusing your issue and thanks for the feedback.
