### ISSUE TITLE
MultiProgress: should prune leading progress bars that have become `DoneVisible` or `DoneHidden`

### ISSUE THREAD

**Issue by chris-laplante** [console-rs/indicatif#426]
Consider this small example program:

```rust
use std::thread;
use std::time::Duration;

use indicatif::{MultiProgress, ProgressBar, ProgressFinish};

fn main() {
    let m = MultiProgress::new();
    let height = console::Term::stdout().size().0;

    for i in 0..(height + 1) {
        let p1 = m.add(
            ProgressBar::new_spinner()
                .with_message(format!("p{}", i))
                .with_finish(ProgressFinish::AndLeave),
        );
        p1.enable_steady_tick(Duration::from_millis(50));
        thread::sleep(Duration::from_millis(200));
    }
}
```

It creates one more spinner that there are lines in the terminal. Here is a video of it running:

https://user-images.githubusercontent.com/40474653/166507072-efdbaf25-82e5-4f25-91ac-e6ab51db2314.mp4

Since we never call `MultiProgress::remove` on `ProgressBar`s that are dropped/finished (see #419), bars are always redrawn even when they don't need to be. When the number of bars (_n_) becomes greater than terminal lines (_m_), on each draw `MultiProgress` will clear the last _m_ lines but write _n_ lines, leaving _m - n_ lines in the scrollback history.

I propose the following algorithm. On each `MultiProgress:draw`, iterate over the bars in order (according to `MultiState::ordering`) and `take_while(|bar| bar.is_finished())`. This set of leading progress bars is then pruned by calling `MultiProgress:remove` on each one. This ensures we are not re-drawing bars that don't need to be redrawn and that we are some reclaiming memory. 

The wrinkle is that `MultiState` cannot currently get at the `ProgressState` to check `is_finished()`, so we will need to restructure some code.

**Comment by djc** [comment]
This sounds reasonable. I don't have a deep understanding of `MultiProgress` paged in right now and the video doesn't want to play for me ("Video can't be played because the file is corrupt" -- Firefox on macOS), but I'd be happy to review a PR for this.
