### ISSUE TITLE
Start a chat

### ISSUE THREAD

**Issue by djc** [console-rs/indicatif#432]
@chris-laplante I've been thinking it might be nice to have a chat venue for discussing indicatif. Are you on Discord? I registered a crates server and was thinking we could make a channel there. (Probably going to onboard some other crates that I work on, too.)

**Comment by chris-laplante** [comment]
Good idea! Yes, I've got discord. Do you need my username?

**Comment by djc** [comment]
Here's an invite: https://discord.com/channels/976380008299917365/976573995723931649.

**Comment by chris-laplante** [comment]
> Here's an invite: https://discord.com/channels/976380008299917365/976573995723931649.

Hmm doesn't seem to have worked. Could you please post a new link?

**Comment by djc** [comment]
https://discord.gg/XMKbU2Py
