### ISSUE TITLE
Spinners no longer advance

### ISSUE THREAD

**Issue by rteabeault** [console-rs/indicatif#433]
It appears that commit 6697ac3472010e54589c14a485512da543b0c923 has broken spinners. After this commit spinners no longer spin.

Run `cargo run --example yarnish` before and at this commit to see the difference.

**Comment by chris-laplante** [comment]
Good catch, thanks! I'm working on a fix now and will add a test so it doesn't happen again.

**Comment by chris-laplante** [comment]
@djc any idea why we check for `tick != 0`?

https://github.com/console-rs/indicatif/blob/main/src/state.rs#L106

**Comment by djc** [comment]
No, I don't quite understand why we check for `tick != 0`. I think this was introduced all the way back in a889b3ae0ea4c77ebe5b6df9e5af527cb703c9a9? My intuition was that it's maybe a sentinel for if there's even a spinner kind of thing that we need to tick, but I don't think that's it?
