### ISSUE TITLE
Add custom formatting for {elapsed}

### ISSUE THREAD

**Issue by sunshowers** [console-rs/indicatif#440]
Hi there -- thanks for the library! I'm having a lot of fun integrating it into [cargo-nextest](https://nexte.st).

A little issue I'm running into is that currently there's only two ways to format elapsed time: with `{elapsed}` which outputs `20s`, `42m` etc, and as `{elapsed_precise}`. There's already a convention for how times are output in nextest, and I'd like to have a custom formatter that takes a `Duration` and formats it according to that convention.

I have steady ticks enabled, and I can't use my own formatting (in e.g. the prefix) because new events might not show up within the right resolution.

I was thinking maybe `ProgressStyle` could accept methods `elapsed_formatter(Box<Fn(Duration, &mut fmt::Formatter) -> fmt::Result + Send + Sync>)` and `eta_formatter` which would do custom formatting. What do you think?

The reason to have separate methods would be that in my use case I'd like to output the elapsed time with a greater resolution (every 100ms) than the ETA.

**Comment by sunshowers** [comment]
For now I've switched to using `elapsed_precise` so it's not a huge issue for me, but it would be cool to think about this I think.

**Comment by djc** [comment]
I think the main branch has facilities for this, maybe have a look? There's also an open PR to further extend that interface.

**Comment by sunshowers** [comment]
Excellent, looks like it has the ability to set custom keys. That should work, thanks!
