### ISSUE TITLE
using wide unicode characters in `progress_chars` results in a too wide bar being drawn

### ISSUE THREAD

**Issue by whirm** [console-rs/indicatif#455]
I've just upgraded my project to `0.17.0` from `0.16.2` and I've noticed that a bar that's using 

```rust
    template.progress_chars("🔐🔑🕓");
```
now draws incorrectly:

![image](https://user-images.githubusercontent.com/529494/182143722-78da640e-e150-4d14-855a-9d5903bff434.png)

With 0.16.2 it worked just fine:

![image](https://user-images.githubusercontent.com/529494/182143517-1f9d898f-19c1-424b-9280-68cf4e905266.png)

line on my Cargo.toml:

```toml
indicatif = { version = "0.17.0", features = ["improved_unicode", "tokio"] }
```

Thanks for this project!

**Comment by djc** [comment]
Oops, sorry about that! Looks like I made a typo while refactoring in https://github.com/console-rs/indicatif/commit/d7851c7a467313571d71133b1729af9c5dd3b2ae, fix submitted in #456.
