### ISSUE TITLE
Where is the list of template keys

### ISSUE THREAD

**Issue by Jedsek** [console-rs/indicatif#465]
The doc tells me that I should review [the list of template keys](https://docs.rs/indicatif/0.17.0/indicatif/style/index.html#templates), but I got nothing.

**Comment by Jedsek** [comment]
Wrong link?

**Comment by djc** [comment]
I guess it should link to https://docs.rs/indicatif/0.17.0/indicatif/index.html#templates.

**Comment by Jedsek** [comment]
Yes, please fix it.

**Comment by djc** [comment]
Where did you find the link? Would be great if you could submit a PR.

**Comment by Jedsek** [comment]
Ok, I just found wrong link in this place
