### ISSUE TITLE
indicatif::style::ProgressTracker is not `Sync`

### ISSUE THREAD

**Issue by rctlmk** [console-rs/indicatif#467]
Is ```Sync``` bound missing by mistake? After updating my project's dependency from "0.17.0-rc.8" to "0.17.0" it doesn't compile anymore because of this:
```rust
lazy_static! {
    static ref IDLE_STYLE: ProgressStyle = ProgressStyle::with_template("{prefix:.dim} {msg:.cyan.dim}").unwrap();
}
```
```
486 | / lazy_static! {
487 | |     static ref IDLE_STYLE: ProgressStyle = ProgressStyle::with_template("{prefix:.dim} {msg:.cyan.dim}").unwrap();
488 | | }
    | |_^ `(dyn ProgressTracker + 'static)` cannot be shared between threads safely
```
Considering this struct from [`test_stateful_tracker()`](https://github.com/console-rs/indicatif/blob/20a857a4ee42e29664e5fd1259b72a5563add8bd/src/style.rs#L749):
```rust
#[derive(Debug, Clone)]
struct TestTracker(Arc<Mutex<String>>);
```
doesn't this mean it needs to be ```Sync``` anyway? I'm new at this Rust thread safety thing, I'm sorry if I'm missing something obvious.

**Comment by djc** [comment]
Yeah, we should probably fix that... It's technically a semver-incompatible change though. @chris-laplante what do you think, should we try to sneak this into 0.17.1 and hope no one has written a `!Send` `ProgressTracker` or bump to 0.18 instead?

**Comment by chris-laplante** [comment]
> Yeah, we should probably fix that... It's technically a semver-incompatible change though. @chris-laplante what do you think, should we try to sneak this into 0.17.1 and hope no one has written a `!Send` `ProgressTracker` or bump to 0.18 instead?

I really doubt anyone has written a `!Send` let alone found out about and used `ProgressTracker` yet. It's probably fine to sneak it into 0.17.1.

**Comment by rctlmk** [comment]
> hope no one has written `!Send` `ProgressTracker`

@djc, I hope you mean `!Sync`, because ```pub trait ProgressTracker: Send```. If not, then it is really confusing. Also, I made a little fix (potentially without breaking anything else), should I make a PR?

**Comment by djc** [comment]
PR would be great!
