### ISSUE TITLE
Templates: broken link in docs

### ISSUE THREAD

**Issue by Walther** [console-rs/indicatif#470]
https://docs.rs/indicatif/0.17.0/indicatif/style/struct.ProgressStyle.html#method.template

> Sets the template string for the progress bar
> Review the list of [template keys](https://docs.rs/indicatif/0.17.0/indicatif/style/index.html#templates) for more information.

Links to https://docs.rs/indicatif/0.17.0/indicatif/style/index.html#templates which contains no further information.

With a bit of searching I think the new location might be here at the root? https://docs.rs/indicatif/latest/indicatif/#templates

**Comment by djc** [comment]
Is this a duplicate of #465 (which was fixed in #469)?

**Comment by Walther** [comment]
Ah nice! Closing as duplicate.
