### ISSUE TITLE
0.7.2 release planning

### ISSUE THREAD

**Issue by djc** [console-rs/indicatif#488]
As requested in #484. Currently on main:

* Implement multi-line progress message support (#443, thanks to @happenslol)
* Use portable-atomic to fix build on some 32-bit platforms (#484, thanks to @messense)
* Reset estimator of progress rate on backwards movement (#483, thanks to @rlee287)
* Bumped the MSRV to 1.56 (#482)

@chris-laplante do you see any blockers?

**Comment by chris-laplante** [comment]
Nothing on my end. I think we're good to release!

**Comment by messense** [comment]
Ping

**Comment by djc** [comment]
Filed #492. Also merged #491.

**Comment by djc** [comment]
Published: https://github.com/console-rs/indicatif/releases/tag/0.17.2. @messense sorry it took me so long!
