### ISSUE TITLE
per_sec and eta values fluctuate wildly from one tick to the next

### ISSUE THREAD

**Issue by shssoichiro** [console-rs/indicatif#494]
It seems that this originated in 71e7eaab9070f2cc34e9002074fe28c9f3fb371f.

The previous behavior was that the per_sec and eta values would be relatively steady throughout the life of the progress bar, as they simply calculated `pos / (now - start_time)`.

The new behavior instead calculates `(pos - prev_pos) / (now - prev_time)`. Since this no longer has the effect of averaging out fast and slow spikes since the start of the progress bar, it causes the values in per_sec and eta to fluctuate wildly between each tick. In my opinion, this is undesirable.

**Comment by djc** [comment]
I think this is the discussion in #394. It could really use someone to dig in and come up with a good plan, and I'm not sure I'll have time for that in the near term.

**Comment by teor2345** [comment]
Closed by #539?

**Comment by djc** [comment]
Probably! If not, feel free to reopen.
