### ISSUE TITLE
Setting length to `None` to change a bar to a spinner, and back

### ISSUE THREAD

**Issue by azriel91** [console-rs/indicatif#506]
Heya, would allowing a progress bar's length to be set to `None` be a sensible thing to support?

Currently `ProgressBar::set_length` takes `len: u64`, and internally sets its state's length to `Some(len)`. In my usage of `indicatif`, I want to:

* Render some progress bars, being "empty bars"
* Render progress bars during a first execution to discover units of work.
* When the units of work are discovered, I'd like to set the length of a progress bar to `None` or `Some(len)`, depending on the discovered work.

That said, as it stands, I think I could achieve the same effect by removing and adding bars, instead of reusing an existing bar.

**Comment by djc** [comment]
Yeah, I'm not sure it makes sense to support this use case. You could instead set the length to 0, or remove/add bars as needed.

**Comment by azriel91** [comment]
cool thanks!
