### ISSUE TITLE
`inc` is call before actual work in examples

### ISSUE THREAD

**Issue by tatref** [console-rs/indicatif#521]
Hi,

In some examples, `inc` is call before "work", for example in the `single.rs` example, we call `inc`, then `sleep` the next line:

https://github.com/console-rs/indicatif/blob/fb8d0e0c912104d30554d3a1ce09990f3bd430a8/examples/single.rs#L9

Should it be called after the heavy lifting?

**Comment by djc** [comment]
Probably. Want to submit a PR?

**Comment by tatref** [comment]
Sure! I just wanted to be sure that my assumption was correct

**Comment by chris-laplante** [comment]
Closing since PR was merged
