### ISSUE TITLE
MultiProgress with lots of progress bars

### ISSUE THREAD

**Issue by Timmmm** [console-rs/indicatif#53]
If you specify more progress bars than rows in your terminal window then it prints all the progress bars as new lines - it doesn't erase them properly.

I guess ideally it would maintain an internal buffer of what the output should be and only try to print the visible lines. When the terminal is resized it could reveal more lines.

**Comment by ClementTsang** [comment]
This seems to still be an issue, at least for me on macOS on 0.17.0-beta.1.

**Comment by djc** [comment]
If someone wants to submit a PR for this, I'd be happy to mentor/review.

**Comment by ClementTsang** [comment]
I can try to take a look over the weekend, seems like an interesting problem to tackle.

**Comment by JesseAtSZ** [comment]
> I can try to take a look over the weekend, seems like an interesting problem to tackle.
I have encountered similar problems. Is there any progress on this problem?

**Comment by djc** [comment]
Not that I know of.

**Comment by chris-laplante** [comment]
Thanks to work by @oli-obk in #563, I think this can now be marked as resolved.
