### ISSUE TITLE
Release request -- 0.17.4

### ISSUE THREAD

**Issue by azriel91** [console-rs/indicatif#541]
Heya, would you mind publishing a new version?

I went through the merged PRs since the last release and notable changes are:

* WASM compatibility added (#513, #514).
* Rate limiting for TermLike targets (#526).
* Handle line wrapping when progress bar rendering exceeds terminal length (#520, #533).
* A number of specific usage bug fixes.

I think the line wrapping issue is the one many people are keen to pick up :fist_raised:!

**Comment by djc** [comment]
See #542.
