### ISSUE TITLE
How do I make `percent` round down?

### ISSUE THREAD

**Issue by ajeetdsouza** [console-rs/indicatif#544]
I'd like to make the `percent` field show the `floor` of the actual value. The motivation for this is that I don't want the percentage to show as `100%` till the last block is completed.

**Comment by ajeetdsouza** [comment]
That works, thanks! Some examples / better documentation of it would be nice, I did go through the documentation but I couldn't figure out what `ProgressTracker` was till I saw your comment.

**Comment by djc** [comment]
If you would be able to submit a PR with improved documentation and/or examples, that would be great!
