### ISSUE TITLE
Add a default clear mode

### ISSUE THREAD

**Issue by mitsuhiko** [console-rs/indicatif#6]
`ProgressBar::finish` should clear with a style default setting. This would also help `Drop` automatically clear progress bars if wanted.

eg:

```rust
let style = ProgressStyle::new().clear_on_finish(true);
```

Then the progress bar will automatically disappear if someone calls `finish()` on it.

**Comment by djc** [comment]
We now have 6 different finish modes that can be used, so I believe this is fixed.
