### ISSUE TITLE
Question: How to get latest progress bar state string

### ISSUE THREAD

**Issue by Halimao** [console-rs/indicatif#617]
### Summary
Is there a way that we could get the latest progress bar state just like output in the terminal, something like following cases, get the progress bar state string that is shown to user

### Case1: downloading or download process terminate
```
[00:00:06] [###################################--------] 67.79 MiB/97.79 MiB (5s) -
```

### Case2: downloaded successfully
```
[00:00:06] [########################################] 97.79 MiB/97.79 MiB (0s) - Download complete
```

**Comment by chris-laplante** [comment]
By state string, do you mean the message? (e.g. "Download complete" in Case 2) Or do you mean the entire line that is displayed (including the `####` characters and everything)? 

I assume you mean the latter. There is no built-in way, but you can probably make it work by implementing the [`TermLike`](https://github.com/console-rs/indicatif/blob/main/src/term_like.rs) trait and sort of "fork" (or [tee](https://man7.org/linux/man-pages/man1/tee.1.html)) the output to the actual terminal and an [`InMemoryTerm`](https://github.com/console-rs/indicatif/blob/main/src/in_memory.rs). Then you use the `InMemoryTerm` to get the output.

**Comment by Halimao** [comment]
@chris-laplante Hi sir, thanks for your reply. I indeed mean the latter, get the entire line that is displayed to user. I will try the way you suggested, thanks again.

**Comment by chris-laplante** [comment]
> @chris-laplante Hi sir, thanks for your reply. I indeed mean the latter, get the entire line that is displayed to user. I will try the way you suggested, thanks again.

Sure thing, just let me know if have issues with it :)
