### ISSUE TITLE
Git repo is missing tag for v0.17.7

### ISSUE THREAD

**Issue by rlee287** [console-rs/indicatif#619]
A cursory dig through the git history suggests that 0c037edc86449d84aa457d7d5db80b4166c18d6b should be tagged as 0.17.7. However, this should be confirmed before pushing the tag and closing this issue.

**Comment by djc** [comment]
Done. As a volunteer maintainer, the less important stuff like this sometimes falls through the cracks. If this kind of thing is important to you or your organization, please consider [sponsoring](https://github.com/sponsors/djc) indicatif maintenance.
