### ISSUE TITLE
examples/fastbar.rs rendering is different on Windows git-bash than CMD or PowerShell

### ISSUE THREAD

**Issue by DBY047** [console-rs/indicatif#634]
- OS: Windows 10
- Indicateif version: 0.17.8
- Shells: Git Bash vs Powershell or CMD (Window Terminal)

I saw a similar behavior on a program I wrote. Whether I use finish or finish_and_clear, printLn! called after is printed on the same line as the progress bar. I saw the same behavior on fastbar example.

Rendering on Command Prompt:
![image](https://github.com/console-rs/indicatif/assets/90046702/a938732f-ef30-4e2e-97b4-0cfee975a6c0)

Redering on git bash
![image](https://github.com/console-rs/indicatif/assets/90046702/412c282e-8be6-4141-8ab0-8ec0082fdc02)

Also, it looks like wide_bar is not handled the same way on all terminals. I can't find out what to change on my code or on git-bash configuration so wide_bar is rendered wide.

Thanks,

**Comment by djc** [comment]
Sorry, I won't have time to look into this. Open to reviewing a PR if you figure out why this happens, though!

**Comment by DBY047** [comment]
@djc Both issue are caused by GetConsoleScreenBufferInfo in console/mod.rs returning 0. 

I found a fix here https://github.com/mintty/mintty/issues/1188#issuecomment-1333257062 that fixes both wide_bar not beeig wide and the printLn! not beeing printed as a new line.
