### ISSUE TITLE
[Meta] missing release entries for 0.17.6 and up

### ISSUE THREAD

**Issue by hasezoey** [console-rs/indicatif#635]
I have noticed that versions `0.17.6` and up dont have a github release (but previous `0.17.x` did), in addition there is no changelog which could be used instead.

**Comment by hasezoey** [comment]
also in addition i noticed there is no git tag for `0.17.8` yet, but is released to crates

**Comment by smoelius** [comment]
FYI: https://github.com/console-rs/indicatif/issues/619

**Comment by djc** [comment]
Added the missing changelog entries.
