### ISSUE TITLE
Using ⚙️ emoji in ProgressBar spinner message causes unnessecary line breaks

### ISSUE THREAD

**Issue by Silvea12** [console-rs/indicatif#638]
For some reason, the width of ⚙️ (a 2-char emoji) seems to have its length mis-calculated, and as a result puts every single refresh on a new line.
As seen in the Dioxus CLI when watching a build. Reproduced in both Konsole 24.02.1 and JetBrains RustRover 2023.3 EAP on Linux with both the Fira Code and Hack fonts.

Note: this only happens with ⚙️, not with ⚙.

Minimal reproduction code:
```toml
[dependencies]
indicatif = "0.17.8"
```

```rust
use std::time::Duration;
use indicatif::ProgressBar;

fn main() {
        let mut bar = ProgressBar::new_spinner();
        bar.enable_steady_tick(Duration::from_millis(200));
        bar.set_message("⚙️ Hi there!");
        std::thread::sleep(Duration::from_secs(5));
}
```

**Comment by djc** [comment]
You probably just need to enable some of the Cargo features for proper Unicode support?

**Comment by Silvea12** [comment]
Gave that a shot - same bug. Seems to happen regardless of if `improved_unicode` is enabled or not.

**Comment by djc** [comment]
Well, maybe you can have a look at how `indicatif::style::measure()` fails with your example string, and if there's something that can be done to improve it?

**Comment by djc** [comment]
> Additionally, in the ratatui issue that links to it, the crate https://github.com/jameslanska/unicode-display-width/ is mentioned as a possible replacement. I haven't tested yet, but it'd need to be moved into the `console` crate instead.

Why would need to be moved into the console crate? I'd be okay with taking on the extra dependency on this (only if `improved_unicode` is enabled).

**Comment by Silvea12** [comment]
Could do, just feels weird to me to use the console crate for so few parts. But it'd just be a matter of replacing all occurrences of `console::measure_text_width()` with the `width()` method from the mentioned crate, maybe putting `console::ansi::strip_ansi_codes()` in before it depending on if you wanted that feature flag - I'm not sure what your intent is with dealing with ANSI there (though I'd assume you would want to strip it)

**Comment by djc** [comment]
It's separation of concerns -- Unicode and dealing with the console are really separate domains so using different dependencies for these makes some amount of sense to me.

**Comment by Silvea12** [comment]
Works for me then. I will try to find some time in the next couple days to whip up an MR.

**Comment by Silvea12** [comment]
Actually hol up - while it *is* in theory separation of concerns, console-rs already has unicode width, which is why I flagged up maybe doing it in console anyway. We 100% sure we don't want to put it over in console-rs's own code? I feel like the fact that Cargo.toml has `console/unicode-width` we should be fixing it there.

 (Hi I'm still waking up, so I'm a bit slower to catch things like this :P)

**Comment by djc** [comment]
That's fair! Would be nice but console has had pretty slow maintenance recently. Okay, submit a PR to it and please ping me on it so I can have a look.

**Comment by Silvea12** [comment]
So, I've run a test. The patches work, but it appears it also only returns 1 or 2 for `unicode_display_width::is_double_width()` (well, boolean, but it means 2 if true or 1 if false) which would be used for `fn char_width(c: char) -> usize {}` As a result, I'm a little nervous to add it simply on the face of it, as it appears to throw out the option and `unwrap_or(0)` that was previously there.

For the sake of completeness, here are patch files with the changes I intended to make - but I'm not sure if these should be applied. Not sure if I'm going to break something elsewhere.

Here's the patches:
<details><summary>indicatif.patch</summary>

```patch
Index: src/style.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/style.rs b/src/style.rs
--- a/src/style.rs	(revision HEAD)
+++ b/src/style.rs	(revision Staged)
@@ -39,12 +39,12 @@
     s.chars().map(|x| x.to_string().into()).collect()
 }
 
-#[cfg(feature = "unicode-width")]
+#[cfg(feature = "unicode-display-width")]
 fn measure(s: &str) -> usize {
-    unicode_width::UnicodeWidthStr::width(s)
+    unicode_display_width::width(s) as usize
 }
 
-#[cfg(not(feature = "unicode-width"))]
+#[cfg(not(feature = "unicode-display-width"))]
 fn measure(s: &str) -> usize {
     s.chars().count()
 }
Index: Cargo.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Cargo.toml b/Cargo.toml
--- a/Cargo.toml	(revision HEAD)
+++ b/Cargo.toml	(revision Staged)
@@ -13,14 +13,15 @@
 exclude = ["screenshots/*"]
 
 [dependencies]
-console = { version = "0.15", default-features = false, features = ["ansi-parsing"] }
+#console = { version = "0.15", default-features = false, features = ["ansi-parsing"] }
+console = { path = "console", default-features = false, features = ["ansi-parsing"] }
 futures-core = { version = "0.3", default-features = false, optional = true }
 number_prefix = "0.4"
 portable-atomic = "1.0.0"
 rayon = { version = "1.1", optional = true }
 tokio = { version = "1", optional = true, features = ["io-util"] }
 unicode-segmentation = { version = "1", optional = true }
-unicode-width = { version = "0.1", optional = true }
+unicode-display-width = { version = "0.3.0", optional = true }
 vt100 = { version = "0.15.1", optional = true }
 
 [dev-dependencies]
@@ -35,8 +36,8 @@
 instant = "0.1"
 
 [features]
-default = ["unicode-width", "console/unicode-width"]
-improved_unicode = ["unicode-segmentation", "unicode-width", "console/unicode-width"]
+default = ["unicode-display-width", "console/unicode-display-width"]
+improved_unicode = ["unicode-segmentation", "unicode-display-width", "console/unicode-display-width"]
 in_memory = ["vt100"]
 futures = ["dep:futures-core"]
```
</details>


<details><summary>console.patch</summary>

```patch
Index: src/utils.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/utils.rs b/src/utils.rs
--- a/src/utils.rs	(revision HEAD)
+++ b/src/utils.rs	(revision Staged)
@@ -707,12 +707,11 @@
 }
 
 fn str_width(s: &str) -> usize {
-    #[cfg(feature = "unicode-width")]
+    #[cfg(feature = "unicode-display-width")]
     {
-        use unicode_width::UnicodeWidthStr;
-        s.width()
+        unicode_display_width::width(s) as usize
     }
-    #[cfg(not(feature = "unicode-width"))]
+    #[cfg(not(feature = "unicode-display-width"))]
     {
         s.chars().count()
     }
@@ -720,12 +719,14 @@
 
 #[cfg(feature = "ansi-parsing")]
 fn char_width(c: char) -> usize {
-    #[cfg(feature = "unicode-width")]
+    #[cfg(feature = "unicode-display-width")]
     {
-        use unicode_width::UnicodeWidthChar;
-        c.width().unwrap_or(0)
+        match unicode_display_width::is_double_width(c) {
+            true => 2,
+            false => 1,
+        }
     }
-    #[cfg(not(feature = "unicode-width"))]
+    #[cfg(not(feature = "unicode-display-width"))]
     {
         let _c = c;
         1
@@ -873,7 +874,7 @@
         measure_text_width(&s),
         if cfg!(feature = "ansi-parsing") {
             3
-        } else if cfg!(feature = "unicode-width") {
+        } else if cfg!(feature = "unicode-display-width") {
             17
         } else {
             21
@@ -882,7 +883,7 @@
 }
 
 #[test]
-#[cfg(all(feature = "unicode-width", feature = "ansi-parsing"))]
+#[cfg(all(feature = "unicode-display-width", feature = "ansi-parsing"))]
 fn test_truncate_str() {
     let s = format!("foo {}", style("bar").red().force_styling(true));
     assert_eq!(
Index: Cargo.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Cargo.toml b/Cargo.toml
--- a/Cargo.toml	(revision HEAD)
+++ b/Cargo.toml	(revision Staged)
@@ -13,13 +13,13 @@
 rust-version = "1.56.0"
 
 [features]
-default = ["unicode-width", "ansi-parsing"]
+default = ["unicode-display-width", "ansi-parsing"]
 windows-console-colors = ["ansi-parsing"]
 ansi-parsing = []
 
 [dependencies]
 libc = "0.2.99"
-unicode-width = { version = "0.1", optional = true }
+unicode-display-width = { version = "0.3.0", optional = true }
 lazy_static = "1.4.0"
 
 [target.'cfg(windows)'.dependencies]
```
</details>

**Comment by Silvea12** [comment]
I have created a pair of PRs that fully replace the API. Worth a note: there's a cast from a u64 to a usize in there, done to avoid changing APIs too much - also mentioned at https://github.com/console-rs/console/pull/210/files#r1552479044

**Comment by Silvea12** [comment]
Continuing the conversation from the PRs here because this is more meta to the whole change. Worth a note in the original unicode-width crate:
> Most shells including bash and zsh and most terminal emulators do not support the zero width joiner.

> If your application needs the width as rendered by any of these systems, DO NOT use this crate. This project is more suited towards editors that wrap a web engine such as Chromium with Electron (e.g. VS Code).

Given this info, I'm not really sure what we want to be doing here at this point. They suggest one solution involving probing the terminal for information on how it prints things using cursor widths etc, but this sounds like a far more involved and not entirely portable solution.

I'm considering closing the PRs unless something better is thought of - I think the route I'm going down is just trading one evil for another, as neither option is actually portable.

**Comment by djc** [comment]
Ah, that's fair. Maybe the right fix is to advocate that Dioxus uses the other gear? (On my Mac the gears in your OP look identical anyway -- in the browser, at least.)

**Comment by Silvea12** [comment]
The gear looks identical - the problem is that it sends a bunch of newlines because it assumes the gear is 1 wide instead of 2, and as a result generates an extra padding space and thus an unnecessary newline. See here:
![image](https://github.com/console-rs/indicatif/assets/3120639/69a8444c-f3e0-46fe-9ed8-32394fc39b23)

**Comment by Silvea12** [comment]
I'm closing the PRs, but leaving the issue open in case someone else wishes to pick up the mantle - I am short on time and consider the PRs unsuitable for fixing the issue, so I have to put this one aside.

**Comment by mkenigs** [comment]
Is there any way to work around this other than just not using 2-char emojis?

**Comment by djc** [comment]
I don't think so, but am open to any ideas you have (after reading the discussion here, in #639 and in https://github.com/console-rs/console/pull/210).

**Comment by Jules-Bertholet** [comment]
`unicode-width` 1.12 (released today) now supports U+FE0F 2-char emojis, including ⚙️ (skin tone modifiers and ZWJ emojis remain unsupported).

**Comment by djc** [comment]
@Jules-Bertholet that sounds great. @Silvea12 so can we close this now?

**Comment by Silvea12** [comment]
> that sounds great. @Silvea12 so can we close this now?

Hey! I've been meaning to get to this, but I've fallen ill with COVID. I'll get back to you on it when I'm better.

For me, a working thing is to install latest indicatif, and then running the above sample code and not seeing the extra newlines. That'll either result in this being closed, or a PR so it can be closed.

I'll get to it once I'm feeling better! Sorry for the delay.

**Comment by Silvea12** [comment]
Update: I can confirm a clean install works on my system, where I was experiencing the issue. Closing this, thanks @Jules-Bertholet for the update!

**Comment by djc** [comment]
Thanks for the confirmation, hope you feel better soon!
