### ISSUE TITLE
MultiProgress second ProgressBar extremely delayed

### ISSUE THREAD

**Issue by LDprg** [console-rs/indicatif#643]
I am having a MultiProgress where I add a ProgressBar after another finishes. However it gets displayed like 4-6 seconds after the first one finishes.

I am making heavy use of tokio if this matters.

**Comment by djc** [comment]
Unless you can come up with a reproducible example it willbe hard to dig into this more.

**Comment by LDprg** [comment]
Will send one. I wasn't able to access my laptop with the code until now (the reason why I didn't include one)

**Comment by LDprg** [comment]
Got the time today to inspect my code and found a bug delaying the creation of the progress bar. However I was just a small implementation fault from my.

Sry for bothering you.
