### ISSUE TITLE
How to add information to span spinner

### ISSUE THREAD

**Issue by arifd** [console-rs/indicatif#680]
Hi! This is a really awesome crate, but I'm unsure how to add information, not necesarily change style.

let's say I have this generic function
```rs
  #[tracing::instrument]
    fn test() {
        std::thread::sleep(std::time::Duration::from_secs(60));
    }
 ```
 
 All I get in my terminal is: 
<img width="79" alt="image" src="https://github.com/user-attachments/assets/9507f145-9372-45d7-9cd9-2389c52a97c5" />
_(not sure how to call this, so I called it "span spinner" in title!)_

I would like to add file and line info.

I thought something like this would do it:

```rs
let indicatif = IndicatifLayer::new();
let indicatif_layer = tracing_subscriber::fmt::layer()
    .with_file(true)
    .with_line_number(true)
    .with_writer(indicatif.get_stderr_writer())
    .with_filter(LevelFilter::INFO);
```

But it makes no difference to the output

**Comment by djc** [comment]
I have no clue what you're up to. Are you cobbling together code with LLMs?

**Comment by arifd** [comment]
Haha, I'm not really sure what you are asking.

let me make you a minimal reproducible example:

Let's have this as our setup for both cases:
```rs
use tracing_subscriber::{layer::SubscriberExt as _, util::SubscriberInitExt as _};

#[tracing::instrument]
fn test() {
    #[tracing::instrument]
    fn test() {
        std::thread::sleep(std::time::Duration::from_secs(1));
    }

    test();

    test();
}
```

Now in a typical example with tracing and pretty:
```rs
fn main() {
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::fmt::layer()
                .with_span_events(FmtSpan::FULL)
                .pretty(),
        )
        .init();

    test();
}
```

There is file and line information available in the spans when they are printed:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/a02f1270-5e9f-4fd4-9b2e-96ede7acf041" />

(see main.rs:7)

I was wondering if this information is available in tracing indicatif, and how to make it visible if so, because with tracing_indicatif:

```rs
fn main() {
    let indicatif = tracing_indicatif::IndicatifLayer::new();
    let indicatif_layer =
        tracing_subscriber::fmt::layer().with_writer(indicatif.get_stderr_writer());

    tracing_subscriber::registry()
        .with(indicatif_layer)
        .with(indicatif)
        .init();

    test();
}
```

All I see is this:
<img width="546" alt="image" src="https://github.com/user-attachments/assets/9a9597fc-37fe-4c20-b890-f79d84a24587" />

**Comment by djc** [comment]
Okay, but I have never used tracing-indicatif and am completely unfamiliar with what it does/how it works.

Did you mean to file an issue against it?

**Comment by arifd** [comment]
Ohh I'm so sorry!!! I'm in the wrong repo. :(  apologies for the needless confusion!!
