### ISSUE TITLE
Millisecond support for {elapsed}?

### ISSUE THREAD

**Issue by xSke** [console-rs/indicatif#71]
Would be nice to have optional sub-second precision here.

**Comment by mitsuhiko** [comment]
Would love to get a pull request for this. Seems like a sensible addition.

**Comment by xSke** [comment]
Sure, could do that. Unsure how it should be made optional though, any thoughts on that?

**Comment by djc** [comment]
Current main (release tracked in #318) can have custom template keys that have access to the `ProgressState`.
