### ISSUE TITLE
Add File Wrappers

### ISSUE THREAD

**Issue by mitsuhiko** [console-rs/indicatif#8]
It would be great if one can directly wrap files so it works with `io::copy` and others.

**Comment by dcbishop** [comment]
Could be worth looking at fs_extra. It does filesystem move/copy operations with recursive for directory operations and such. It has a progress callback handle so isn't hard to integrate.

**Comment by mitsuhiko** [comment]
There is now one for readers.

**Comment by djc** [comment]
At this point we have wrappers for `io::Read`, `io::Write` as well as tokio's async I/O traits and several others.
