### ISSUE TITLE
Feature request: Show iteration rate

### ISSUE THREAD

**Issue by ah-** [console-rs/indicatif#82]
Hi,

I'm coming from tqdm in Python and one of my favourite features there is that it shows the current iteration rate, e.g. [229.00it/s]:

```
76%|████████████████████████████         | 7568/10000 [00:33<00:10, 229.00it/s]
```

This is particularly useful if you're watching a process where a slow-down or uptake in iterations can indicate an issue.

I would be great to have something similar in indicatif, so I just wanted to open this issue to start discussing.

From a quick skim over both projects we'd obviously need a formatter in https://github.com/mitsuhiko/indicatif/blob/master/src/style.rs#L116.
It'd also need slightly advanced tracking of iteration times, see `avg_time` here: https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L1011

The smoothing of recent iteration times is really useful, and often more interesting than just total time divided by iterations.

I could imagine the same being useful for e.g. the download example, in addition to seeing 71/220MB are done you'd also know you're getting 15MB/sec.

Edit: Looks like we already have https://github.com/mitsuhiko/indicatif/blob/master/src/utils.rs#L18, so this might be easier than expected.

**Comment by djc** [comment]
This has been implemented for a while now.
